
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop 
  labels:
    app: payment
    project: roboshop 
    tier: app
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector: # replica labels 
    matchLabels:
      app: payment
      project: roboshop 
      tier: app
  template: # pod-definition
    metadata:
      labels:
        app: payment
        project: roboshop 
        tier: app
    spec:
      containers:
      - name: payment
        image: "devopsprocloud/payment:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always 
        resources: 
          requests: 
            cpu: "50m"
            memory: "128Mi"
          limits: 
            cpu: "100m"
            memory: "256Mi"
        envFrom: 
        - configMapRef: 
            name: payment 
        - secretRef: 
            name: payment 