
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    project: roboshop 
    tier: app
spec:
  ports:
  - protocol: TCP 
    port: 8080 #service port 
    targetPort: 8080 #container port 