apiVersion: v1 
kind: ConfigMap
metadata: 
  name: mysql
  namespace: roboshop 
data: 
  MYSQL_DATABASE: "cities"
  MYSQL_ROOT_PASSWORD: RoboShop@1
  MYSQL_USER: shipping
  MYSQL_PASSWORD: RoboShop@1
