apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql 
  namespace: roboshop
  labels: 
    app: mysql
    project: roboshop 
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop 
      tier: db # has to match .spec.template.metadata.label
  serviceName: "mysql"
  # replicas: {{ .Values.statefulset.replicas }}
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop 
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: "devopsprocloud/mysql:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - secretRef: 
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
---