apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis 
  namespace: roboshop
  labels: 
    app: redis
    project: roboshop 
    tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop 
      tier: db # has to match .spec.template.metadata.label
  serviceName: "redis"
  # replicas: {{ .Values.statefulset.replicas }}
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        project: roboshop 
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis 
        volumeMounts:
        - name: redis
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
---