
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop 
  labels:
    app: shipping
    project: roboshop 
    tier: app
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector: # replica labels 
    matchLabels:
      app: shipping
      project: roboshop 
      tier: app
  template: # pod-definition
    metadata:
      labels:
        app: shipping
        project: roboshop 
        tier: app
    spec:
      containers:
      - name: shipping
        #image: "devopsprocloud/shipping:{{ .Values.deployment.imageVersion }}"
        image: "joindevops/shipping:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always 
        resources: 
          requests: 
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"
        envFrom: 
        - configMapRef: 
            name: shipping 