# Creating service
apiVersion: v1 
kind: Service 
metadata: 
  name: web
  namespace: roboshop 
spec: 
  type: LoadBalancer
  selector: 
   app: web  
   project: roboshop 
   tier: web  
  ports:
  - protocol: TCP 
    port: 8080 #service port 
    targetPort: 80 #container port 