# Creating service
apiVersion: v1 
kind: Service 
metadata: 
  name: web
  namespace: roboshop 
spec: 
  type: ClusterIP
  selector: 
   app: web  
   project: roboshop 
   tier: web  
  ports:
  - protocol: TCP 
    port: 80 #service port 
    targetPort: 8080 #container port 