apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::221082195538:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-vgJD55HYcNrE
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::221082195538:user/prem
      username: prem

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 32db5a17-96af-4b01-bc6a-48a8602b513d