
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    project: roboshop 
    tier: app
spec:
  selector:
    app: catalogue
    project: roboshop 
    tier: app
  ports:
  - protocol: TCP 
    port: 8080 #service port 
    targetPort: 8080 #container port 

